language: go
os: linux
sudo: required
go:
  - 1.9.x
go_import_path: github.com/kairen/simple-device-plugin

install:
  - echo "Don't run anything."
before_install:
  - go get -u github.com/golang/dep/cmd/dep
script:
  - dep ensure
  - make test
  - IN_DOCKER=1 make
after_success:
  - bash <(curl -s https://codecov.io/bash)
